name: Android CI

on: [push, pull_request]

jobs:
#  lint:
#    name: Lint Check
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set up JDK 11
#        uses: actions/setup-java@v3
#        with:
#          java-version: '11'
#          distribution: 'temurin'
#          cache: gradle
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#      - name: Run Lint
#        run: ./gradlew lint
#      - name: Upload Lint Results
#        if: always()
#        uses: actions/upload-artifact@v4
#        with:
#          name: lint-results
#          path: app/build/reports/lint-results*.html
#
#  detekt:
#    name: Detekt
#    needs: lint
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set up JDK 11
#        uses: actions/setup-java@v3
#        with:
#          java-version: '11'
#          distribution: 'temurin'
#          cache: gradle
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#      - name: Run Detekt
#        run: ./gradlew detekt
#      - name: Upload Detekt Results
#        if: always()
#        uses: actions/upload-artifact@v4
#        with:
#          name: detekt-results
#          path: build/reports/detekt/

  build:
    name: Build
#    needs: detekt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: my_app
          path: ./apk-output/my_app.apk

  deploygate:
    name: Deploy to DeployGate
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download APK from build
        uses: actions/download-artifact@v4
        with:
          name: my_app
          path: ./apk-output
      - name: List downloaded files
        run: |
          ls -la ./apk-output
          find ./apk-output -type f
      - name: Upload to DeployGate
        uses: DeployGate/deploygate-upload-github-action@v1.0.1
        with:
          api_token: ${{ secrets.DEPLOYGATE_API_TOKEN }}
          owner_name: ${{ secrets.DEPLOYGATE_OWNER_NAME }}
          file_path: ./apk-output/my_app.apk
          message: "Build từ GitHub Actions - Commit: ${{ github.sha }}"
          distribution_name: "CI Build"
          release_note: "Tự động build từ branch ${{ github.ref_name }} - ${{ github.event.head_commit.message }}"