name: Android CI

on: [push, pull_request]

jobs:
#  lint:
#    name: Lint Check
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set up JDK 11
#        uses: actions/setup-java@v3
#        with:
#          java-version: '11'
#          distribution: 'temurin'
#          cache: gradle
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#      - name: Run Lint
#        run: ./gradlew lint
#      - name: Upload Lint Results
#        if: always()
#        uses: actions/upload-artifact@v4
#        with:
#          name: lint-results
#          path: app/build/reports/lint-results*.html
#
#  detekt:
#    name: Detekt
#    needs: lint
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set up JDK 11
#        uses: actions/setup-java@v3
#        with:
#          java-version: '11'
#          distribution: 'temurin'
#          cache: gradle
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#      - name: Run Detekt
#        run: ./gradlew detekt
#      - name: Upload Detekt Results
#        if: always()
#        uses: actions/upload-artifact@v4
#        with:
#          name: detekt-results
#          path: build/reports/detekt/

#  build:
#    name: Build
##    needs: detekt
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set up JDK 11
#        uses: actions/setup-java@v3
#        with:
#          java-version: '11'
#          distribution: 'temurin'
#          cache: gradle
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#      - name: Build with Gradle
#        run: ./gradlew build
#      - name: Upload APK
#        if: success()
#        uses: actions/upload-artifact@v4
#        with:
#          name: my_app
#          path: ./apk-output/*.apk

  deploygate:
    name: Deploy to DeployGate
#    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
#      - name: Build with Gradle
#        run: ./gradlew build
#
#      - name: Distribute App
#        run: |
#          curl \
#            -H "Authorization: token ${{secrets.KEY_DEPLOY}}" \
#            -F "file=@app/build/outputs/apk/develop/debug/app-debug.apk" \
#            -F "message=Any message" \
#            -F "distribution_key=${{secrets.DEPLOYGATE_KEY_DISTRIBUTIONS}}" \
#            -F "release_note=Release Note" \
#            "https://deploygate.com/api/users/cthang429/apps/"
      - name: Tele
        run: |
          curl -F "https://deploygate.com/qr?data=https%3A%2F%2Fdeploygate.com%2Fdistributions%2F4ebff415f38a13a5e2eade34149121419d2e6757&size=178" \
               -F "caption=CI/CD build completed!" \
               "https://api.telegram.org/bot7374015427:AAERC-Q0d_rugIYlEMLLGNe0BsjIrOStJHE/sendPhoto?chat_id=-1002534047063"